server.port=9000
spring.application.name=ms-card


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ingenieria;encrypt=false
spring.datasource.username=Josue
spring.datasource.password=12345


spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
